package org.techascent.composa.theming.color

import androidx.compose.ui.graphics.Color

data class ComposaColor(
    val backgroundAction: Color,
    val backgroundActionAlternative: Color,
    val backgroundActionSubtle: Color,
    val backgroundAppBackground: Color,
    val backgroundErrorBold: Color,
    val backgroundErrorSubtle: Color,
    val backgroundInfoBold: Color,
    val backgroundInfoSubtle: Color,
    val backgroundMarketingBold: Color,
    val backgroundMarketingSubtle: Color,
    val backgroundNeutral: Color,
    val backgroundNeutralBase: Color,
    val backgroundNeutralBold: Color,
    val backgroundNeutralInverse: Color,
    val backgroundNeutralSolid: Color,
    val backgroundNeutralSubtle: Color,
    val backgroundPositiveBold: Color,
    val backgroundPositiveSubtle: Color,
    val backgroundWarningBold: Color,
    val backgroundWarningSubtle: Color,
    val componentButtonBackgroundAction: Color,
    val componentButtonBackgroundActionBlanckDestructivePressed: Color,
    val componentButtonBackgroundActionBlankPressed: Color,
    val componentButtonBackgroundActionDestructive: Color,
    val componentButtonBackgroundActionDestructiveDisabled: Color,
    val componentButtonBackgroundActionDestructivePressed: Color,
    val componentButtonBackgroundActionDisabled: Color,
    val componentButtonBackgroundActionPressed: Color,
    val componentButtonBorderAction: Color,
    val componentButtonBorderActionDestructive: Color,
    val componentButtonBorderActionDestructiveDisabled: Color,
    val componentButtonBorderActionDisabled: Color,
    val componentButtonIconAction: Color,
    val componentButtonIconActionAlternative: Color,
    val componentButtonIconActionDestructive: Color,
    val componentButtonIconActionDestructiveDisabled: Color,
    val componentButtonIconActionDisabled: Color,
    val componentButtonIconActionDisabledAlternative: Color,
    val componentButtonIconActionInverse: Color,
    val componentButtonIconNeutralInverse: Color,
    val componentButtonTextAction: Color,
    val componentButtonTextActionAlternative: Color,
    val componentButtonTextActionDestructive: Color,
    val componentButtonTextActionDestructiveDisabled: Color,
    val componentButtonTextActionDestructivePressed: Color,
    val componentButtonTextActionDisabled: Color,
    val componentButtonTextActionDisabledAlternative: Color,
    val componentButtonTextActionInverse: Color,
    val componentButtonTextNeutralInverse: Color,
    val componentPageIndicatorActive: Color,
    val componentPageIndicatorInactive: Color,
    val componentScreendimmerBackground: Color,
    val decorativeFirstBase: Color,
    val decorativeFirstBasesolid: Color,
    val decorativeFirstBold: Color,
    val decorativeFirstBoldsolid: Color,
    val decorativeFirstIntense: Color,
    val decorativeFirstIntensesolid: Color,
    val decorativeFirstMuted: Color,
    val decorativeFirstMutedsolid: Color,
    val decorativeFirstSubtle: Color,
    val decorativeFirstSubtlesolid: Color,
    val decorativeSecondBase: Color,
    val decorativeSecondBasesolid: Color,
    val decorativeSecondBold: Color,
    val decorativeSecondBoldsolid: Color,
    val decorativeSecondIntense: Color,
    val decorativeSecondIntensesolid: Color,
    val decorativeSecondMuted: Color,
    val decorativeSecondMutedsolid: Color,
    val decorativeSecondSubtle: Color,
    val decorativeSecondSubtlesolid: Color,
    val decorativeThirdBase: Color,
    val decorativeThirdBasesolid: Color,
    val decorativeThirdBold: Color,
    val decorativeThirdBoldsolid: Color,
    val decorativeThirdIntense: Color,
    val decorativeThirdIntensesolid: Color,
    val decorativeThirdMuted: Color,
    val decorativeThirdMutedsolid: Color,
    val decorativeThirdSubtle: Color,
    val decorativeThirdSubtlesolid: Color,
    val iconAction: Color,
    val iconActionAlternative: Color,
    val iconActionAlternativeInverse: Color,
    val iconActionInverse: Color,
    val iconActionMuted: Color,
    val iconActionOnDark: Color,
    val iconDestructive: Color,
    val iconNeutral: Color,
    val iconNeutralAlternative: Color,
    val iconNeutralOnDark: Color,
    val iconNeutralSolid: Color,
    val iconNeutralinverse: Color,
    val strokeAction: Color,
    val strokeActionAlternative: Color,
    val strokeError: Color,
    val strokeInfo: Color,
    val strokeMarketing: Color,
    val strokeNeutral: Color,
    val strokeNeutralBold: Color,
    val strokeNeutralOnDark: Color,
    val strokeNeutralSubtle: Color,
    val strokePositive: Color,
    val strokeWarning: Color,
    val textAction: Color,
    val textActionAlternative: Color,
    val textActionAlternativeInverse: Color,
    val textActionInverse: Color,
    val textActionOnDark: Color,
    val textDestructiveBold: Color,
    val textNeutral: Color,
    val textNeutralAlternative: Color,
    val textNeutralInverse: Color,
    val textNeutralOnDark: Color,
    val textNeutralSolid: Color,
    val textNeutralSubtle: Color,
    val textNeutralSubtleSolid: Color,
    val textPositiveBold: Color,
    val textWarningBold: Color,
    val textWarningBoldAlternative: Color,

    // Domain semantic colours (grouped to avoid DEX register limit)
    val prayer: PrayerColors = PrayerColors(),
    val halal: HalalColors = HalalColors(),
)

data class PrayerColors(
    // ── Scenic / sky ────────────────────────────────────────────────────────────
    val skyStart: Color = Color.Transparent,
    val skyEnd: Color = Color.Transparent,
    val sunBody: Color = Color.Transparent,
    val sunGlow: Color = Color.Transparent,
    val horizon: Color = Color.Transparent,
    // ── Timer ────────────────────────────────────────────────────────────────────
    val timerAccent: Color = Color.Transparent,
    val timerTrack: Color = Color.Transparent,
    // ── Fasting — Suhoor / Iftar ─────────────────────────────────────────────────
    val fastingAccent: Color = Color.Transparent,
    val fastingSubtle: Color = Color.Transparent,
    val iftarAccent: Color = Color.Transparent,
    // ── Quick Access section ─────────────────────────────────────────────────────
    val quickAccessAccent: Color = Color.Transparent,
    // ── Current waqt highlight ───────────────────────────────────────────────────
    val currentWaqtBg: Color = Color.Transparent,
    val currentWaqtText: Color = Color.Transparent,
    // ── Halal scanner ────────────────────────────────────────────────────────────
    val scannerAccent: Color = Color.Transparent,
    val scannerSubtle: Color = Color.Transparent,
    // ── Announcement banner ──────────────────────────────────────────────────────
    val announcementBg: Color = Color.Transparent,
    val announcementAccent: Color = Color.Transparent,
    // ── Generic card background ──────────────────────────────────────────────────
    val cardBg: Color = Color.Transparent,
    // ── Quran reader ─────────────────────────────────────────────────────────────
    val quranPlayingAccent: Color = Color.Transparent,
    // ── Prayer calendar ──────────────────────────────────────────────────────────
    val calendarFridayAccent: Color = Color.Transparent,
    val calendarCardAccent: Color = Color.Transparent,
    val calendarWarmAccent: Color = Color.Transparent,
    // ── Compass ──────────────────────────────────────────────────────────────────
    val compassQiblaAccent: Color = Color.Transparent,
    val compassNorthAccent: Color = Color.Transparent,
    // ── Tasbeeh bead colors ──────────────────────────────────────────────────────
    val tasbeehInactive: Color = Color.Transparent,
    val tasbeehActive: Color = Color.Transparent,
    val tasbeehHighlight: Color = Color.Transparent,
    // ── Night / moon / twilight ──────────────────────────────────────────────────
    val nightSkyStart: Color = Color(0xFF0D1B2A),
    val nightSkyEnd: Color = Color(0xFF1B2838),
    val moonBody: Color = Color(0xFFF5F5DC),
    val moonGlow: Color = Color(0x60F5F5DC),
    val moonCrater: Color = Color(0x30A0A080),
    val starColor: Color = Color(0xFFFFFFFF),
    val twilightSkyStart: Color = Color(0xFF1A237E),
    val twilightSkyEnd: Color = Color(0xFFFF8A65),
    val dawnSkyStart: Color = Color(0xFF283593),
    val dawnSkyEnd: Color = Color(0xFFFFAB91),
)

/**
 * Semantic colour tokens for the Halal Scanner and related features.
 *
 * Status colours are intentionally distinct: certified/possible are green shades,
 * doubtful is amber, not-halal is red, unknown is neutral grey.
 */
data class HalalColors(
    val statusCertified: Color = Color.Transparent,   // HALAL_CERTIFIED → deep green
    val statusPossible: Color = Color.Transparent,    // HALAL_POSSIBLE  → medium green
    val statusDoubtful: Color = Color.Transparent,    // HALAL_DOUBTFUL  → amber
    val statusNotHalal: Color = Color.Transparent,    // NOT_HALAL       → red
    val statusUnknown: Color = Color.Transparent,     // UNKNOWN         → neutral grey
)
