package org.techascent.muslim.prayer.tags

object PrayerTags {
    const val PRAYER_TIME_LOADING_ERROR = "PRAYER_TIME_LOADING_ERROR"
    const val PRAYER_TIME_LOADING = "PRAYER_TIME_LOADING"
    const val PRAYER_TIME_CURRENT_SALAT_CONTENT = "PRAYER_TIME_CURRENT_SALAT_CONTENT"
    const val PRAYER_TIME_INFO_CONTENT = "PRAYER_TIME_INFO_CONTENT"
    const val PRAYER_TIME_IFTAR_TIME_CONTENT = "PRAYER_TIME_IFTAR_TIME_CONTENT"
    const val PRAYER_TIME_COUNTDOWN_TIMER_CONTENT = "PRAYER_TIME_COUNTDOWN_TIMER_CONTENT"
    const val PRAYER_TIME_ALL_SALAT_TIME_CONTENT = "PRAYER_TIME_ALL_SALAT_TIME_CONTENT"
}