name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'  # Triggers build on any branch
  pull_request:
    branches:
      - main  # Triggers build for PRs targeting main

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build
        run: ./gradlew build

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Run Unit Tests
        run: ./gradlew test